### ISSUE TITLE
Lag/hitching/FPS drop experienced in combat

### ISSUE THREAD

**Issue by krizz02** [Kkthnx/KkthnxUI_Legion#73] opened 2016-09-24 18:35 UTC
This is currently with kkthnxUI being the only addon installed. In combat, whenever an attack "hits" an enemy, the game hitches and the FPS drops noticeably very briefly. If it's a large group of enemies and I do something like warrior's whirlwind the FPS drops are then worse. Looks to be tied to combat? I originally had the UI comp installed along a lot of other addons but even after clearing out WTF, cache, and all the addons it still occurs.

**Comment by Kkthnx** [comment] 2016-09-24 20:07
I have had this report before, yet I can reproduce. What class / spec and such are you playing also what area is this happening at?

**Comment by krizz02** [comment] 2016-09-24 20:11
Fury warrior.  So far all the legion world areas.  I will see what happens on a different character, didn't even think to try that.  I can also record video of it happening it that would help.

**Comment by Kkthnx** [comment] 2016-09-24 20:13
Are you on US realms, Also do you have discord? We can discuss this further there and I can help in real time there.

**Comment by uncletusky** [comment] 2016-09-24 20:23
Same thing. I'm on the EU though :-/ 

Updated earlier through Curse client and this problem appeared. Severe dps drops (lags even) when fighting. I thought it was due to new Combat Text but disabling it in options doesn't help.

**Comment by Kkthnx** [comment] 2016-09-24 20:24
What options do you have enable or have you enabled yourself?

**Comment by Kkthnx** [comment] 2016-09-24 20:26
Have you managed a clean install?

The first step, Please attempt to clear your wow cache folder and make sure you are logged out when doing so. This solves many in-game issues.

The second step, This sounds like an addon is causing you trouble. Go ahead and disable all your addons. This can solve many problems in-game. If you still have the issue with KkthnxUI and KkthnxUI_Config enabled after you have already taken these steps, please let us know.

The third step, To potentially resolve issues with your game, follow these steps to restore the default user interface.

Completely exit the game.

Open the World of Warcraft folder.
Rename the Cache, Interface, and WTF folders to CacheOld, InterfaceOld, and WTFOld.
Download a fresh copy of KkthnxUI remove the old folders and place the new ones in.
Relaunch so the changes can take effect.

**Comment by krizz02** [comment] 2016-09-24 20:29
uncletusky, what class and spec are you?

I'm on US realms.  I do have discord in just not home at the moment.  I'll be able to try out another character later though and report back.  It happened with a completely new install of the UI, even after wiping cache, interface and WTF.

**Comment by Kkthnx** [comment] 2016-09-24 20:33
So weird. Both of you are warriors?

**Comment by uncletusky** [comment] 2016-09-24 20:34
Mage. But here disabling all addons helped - trying to pinpoint problem now.

**Comment by Kkthnx** [comment] 2016-09-24 20:38
I'm on my warrior now trying to pinpoint it as well.

**Comment by uncletusky** [comment] 2016-09-24 21:13
Weird, I've re-enabled all addons and now I can't reproduce the problem either. Maybe it's some options fault. I'll play with the config some more and if I find something I'll let you guys know.

**Comment by Kkthnx** [comment] 2016-09-24 21:24
Very weird. I'm rewriting some stuff right now.

**Comment by Kkthnx** [comment] 2016-09-24 21:35
[KkthnxUI_StutterFixTest.zip](https://github.com/Kkthnx/KkthnxUI_Legion/files/491359/KkthnxUI_StutterFixTest.zip)

Please clean install this and test it.

**Comment by Kkthnx** [comment] 2016-09-24 21:35
This could be a result of a memory leak :(

**Comment by krizz02** [comment] 2016-09-24 22:40
Odd, it happens even as soon as I log in.  I'll give everything a test later on tonight.  You work fast.

**Comment by Kkthnx** [comment] 2016-09-24 23:04
Damn. Well This could take some time. My girlfriend isn't getting the issue either. Solid 90 fps in a dungeon and 100+ in the world no drops.

**Comment by krizz02** [comment] 2016-09-24 23:08
No worries, really.  Don't go nuts.  I'll test your test version later.

**Comment by Kkthnx** [comment] 2016-09-24 23:11
Thank you.

**Comment by krizz02** [comment] 2016-09-25 03:26
Okay, completely fresh install of the StutterFixTest and it's there on the Fury warrior.  Does not look to be happening on WW monk (grabbed a bunch of mobs and did the aoe spin kick).  I can work on recording some footage of it if you'd like.

**Comment by Kkthnx** [comment] 2016-09-25 03:56
Okay.

**Comment by Kkthnx** [comment] 2016-09-25 03:57
This doesn't happen on the default UI right?

**Comment by Kkthnx** [comment] 2016-09-25 03:57
Best thing to do is start disabling some of my modules, chat, unit frames, tweaks, and so on.

**Comment by krizz02** [comment] 2016-09-25 03:58
Nope, no hitching when it's all default.  Will do.  I'll get back to you after some testing.

**Comment by Jolly32** [comment] 2016-09-25 14:11
On a Rogue, i deactivated action bars, and the problem went away. fresh install, deleted cache and WTF folder, clean install of addon. all my addons were activated (DBM/Skada) no skins applied. or settings with /settings all, hope this helps.

**Comment by Kkthnx** [comment] 2016-09-25 17:41
Okay so action bars seems to fix the issue for @Jolly32 can anyone else test this please?

**Comment by Kkthnx** [comment] 2016-09-25 18:04
Please test the latest push on GitHub. I reverted a ton of action bar code.

**Comment by nmeitas** [comment] 2016-09-26 06:38
Happened on enhancement shaman too. Apparently the impact of the FPS drops changed on a daily basis. I've managed to get some 'extreme' [video footage](https://youtu.be/lm9jAa2G2A8) of FPS dropping a few days/builds ago. The StutterFixTest build feels way more smooth.

**Comment by Kkthnx** [comment] 2016-09-26 06:41
Try the latest build. Please be sure to clean install.

**Comment by krizz02** [comment] 2016-09-26 20:38
Just tested the latest build, only wiped the previous addon folders.  Left WTF and cached untouched.  Not experiencing the hitching issue on the warrior.

**Comment by Kkthnx** [comment] 2016-09-26 20:58
@nmeitas Can you please test as well so I can finally close this. Be sure to clean install.

**Comment by Jolly32** [comment] 2016-09-26 23:35
ok sorry for the delay, haven't been able to play the game, on my rogue the problem still persists, and my enhanceshaman too, let me try toggling some stuff tonight, and ill report what i find.

**Comment by Jolly32** [comment] 2016-09-26 23:39
as of the latest commits on github, on my shaman and rogue, the lag/hitching has been cleared.

**Comment by nmeitas** [comment] 2016-09-27 06:23
Clean installed latest push. It is indeed a smoother game play experience. Nevertheless I'm still experiencing slight FPS drops while using skills which affect multiple mobs at once, compared to vanilla UI.
Still thankful for such an amazing interface (:

**Comment by Kkthnx** [comment] 2016-10-04 20:11
This is fixed on the beta.

https://github.com/Kkthnx/KkthnxUI_Legion_Beta

**Closed by Kkthnx** 2016-10-04 20:11 UTC
Labels: bug
